services:
  postgres:
    image: postgres
    container_name: todo-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
